/// 终端输入。
///
/// 未来，它可能包含用于禁用回显、禁用输入缓冲以便键盘事件立即发送、查询支持的功能等功能。
interface terminal-input {
    /// 终端的输入端。
    resource terminal-input;
}

/// 终端输出。
///
/// 未来，它可能包含用于查询终端大小、接收终端大小变化通知、查询支持的功能等功能。
interface terminal-output {
    /// 终端的输出端。
    resource terminal-output;
}

/// 接口提供可选的`terminal-input`作为链接时间授权（link-time authority）用于stdin。
interface terminal-stdin {
    use terminal-input.{terminal-input};

    /// 如果stdin连接到终端，则返回一个`terminal-input`句柄，允许进一步与其交互。
    get-terminal-stdin: func() -> option<terminal-input>;
}

/// 接口提供可选的`terminal-output`作为链接时间授权（link-time authority）用于stdout。
interface terminal-stdout {
    use terminal-output.{terminal-output};

    /// 如果stdout连接到终端，则返回一个`terminal-output`句柄，允许进一步与其交互。
    get-terminal-stdout: func() -> option<terminal-output>;
}

/// 接口提供可选的`terminal-output`作为链接时间授权（link-time authority）用于stderr。
interface terminal-stderr {
    use terminal-output.{terminal-output};

    /// 如果stderr连接到终端，则返回一个`terminal-output`句柄，允许进一步与其交互。
    get-terminal-stderr: func() -> option<terminal-output>;
}
